//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppJournalisteClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services/", ConfigurationName="ServiceReference1.GestionArticleWebService")]
    public interface GestionArticleWebService {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services/GestionArticleWebService/AjouterArticleRequest", ReplyAction="http://services/GestionArticleWebService/AjouterArticleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AppJournalisteClient.ServiceReference1.AjouterArticleResponse AjouterArticle(AppJournalisteClient.ServiceReference1.AjouterArticleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/GestionArticleWebService/AjouterArticleRequest", ReplyAction="http://services/GestionArticleWebService/AjouterArticleResponse")]
        System.Threading.Tasks.Task<AppJournalisteClient.ServiceReference1.AjouterArticleResponse> AjouterArticleAsync(AppJournalisteClient.ServiceReference1.AjouterArticleRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services/GestionArticleWebService/SupprimerArticleRequest", ReplyAction="http://services/GestionArticleWebService/SupprimerArticleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AppJournalisteClient.ServiceReference1.SupprimerArticleResponse SupprimerArticle(AppJournalisteClient.ServiceReference1.SupprimerArticleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/GestionArticleWebService/SupprimerArticleRequest", ReplyAction="http://services/GestionArticleWebService/SupprimerArticleResponse")]
        System.Threading.Tasks.Task<AppJournalisteClient.ServiceReference1.SupprimerArticleResponse> SupprimerArticleAsync(AppJournalisteClient.ServiceReference1.SupprimerArticleRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services/")]
    public partial class article : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool dislikeField;
        
        private string idField;
        
        private byte[] imageField;
        
        private bool likeField;
        
        private string texteField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool dislike {
            get {
                return this.dislikeField;
            }
            set {
                this.dislikeField = value;
                this.RaisePropertyChanged("dislike");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
                this.RaisePropertyChanged("image");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool like {
            get {
                return this.likeField;
            }
            set {
                this.likeField = value;
                this.RaisePropertyChanged("like");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string texte {
            get {
                return this.texteField;
            }
            set {
                this.texteField = value;
                this.RaisePropertyChanged("texte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AjouterArticle", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class AjouterArticleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AppJournalisteClient.ServiceReference1.article article;
        
        public AjouterArticleRequest() {
        }
        
        public AjouterArticleRequest(AppJournalisteClient.ServiceReference1.article article) {
            this.article = article;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AjouterArticleResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class AjouterArticleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public AjouterArticleResponse() {
        }
        
        public AjouterArticleResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SupprimerArticle", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class SupprimerArticleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string titre;
        
        public SupprimerArticleRequest() {
        }
        
        public SupprimerArticleRequest(string titre) {
            this.titre = titre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SupprimerArticleResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class SupprimerArticleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public SupprimerArticleResponse() {
        }
        
        public SupprimerArticleResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GestionArticleWebServiceChannel : AppJournalisteClient.ServiceReference1.GestionArticleWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionArticleWebServiceClient : System.ServiceModel.ClientBase<AppJournalisteClient.ServiceReference1.GestionArticleWebService>, AppJournalisteClient.ServiceReference1.GestionArticleWebService {
        
        public GestionArticleWebServiceClient() {
        }
        
        public GestionArticleWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionArticleWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionArticleWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionArticleWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppJournalisteClient.ServiceReference1.AjouterArticleResponse AppJournalisteClient.ServiceReference1.GestionArticleWebService.AjouterArticle(AppJournalisteClient.ServiceReference1.AjouterArticleRequest request) {
            return base.Channel.AjouterArticle(request);
        }
        
        public bool AjouterArticle(AppJournalisteClient.ServiceReference1.article article) {
            AppJournalisteClient.ServiceReference1.AjouterArticleRequest inValue = new AppJournalisteClient.ServiceReference1.AjouterArticleRequest();
            inValue.article = article;
            AppJournalisteClient.ServiceReference1.AjouterArticleResponse retVal = ((AppJournalisteClient.ServiceReference1.GestionArticleWebService)(this)).AjouterArticle(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppJournalisteClient.ServiceReference1.AjouterArticleResponse> AppJournalisteClient.ServiceReference1.GestionArticleWebService.AjouterArticleAsync(AppJournalisteClient.ServiceReference1.AjouterArticleRequest request) {
            return base.Channel.AjouterArticleAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppJournalisteClient.ServiceReference1.AjouterArticleResponse> AjouterArticleAsync(AppJournalisteClient.ServiceReference1.article article) {
            AppJournalisteClient.ServiceReference1.AjouterArticleRequest inValue = new AppJournalisteClient.ServiceReference1.AjouterArticleRequest();
            inValue.article = article;
            return ((AppJournalisteClient.ServiceReference1.GestionArticleWebService)(this)).AjouterArticleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppJournalisteClient.ServiceReference1.SupprimerArticleResponse AppJournalisteClient.ServiceReference1.GestionArticleWebService.SupprimerArticle(AppJournalisteClient.ServiceReference1.SupprimerArticleRequest request) {
            return base.Channel.SupprimerArticle(request);
        }
        
        public bool SupprimerArticle(string titre) {
            AppJournalisteClient.ServiceReference1.SupprimerArticleRequest inValue = new AppJournalisteClient.ServiceReference1.SupprimerArticleRequest();
            inValue.titre = titre;
            AppJournalisteClient.ServiceReference1.SupprimerArticleResponse retVal = ((AppJournalisteClient.ServiceReference1.GestionArticleWebService)(this)).SupprimerArticle(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppJournalisteClient.ServiceReference1.SupprimerArticleResponse> AppJournalisteClient.ServiceReference1.GestionArticleWebService.SupprimerArticleAsync(AppJournalisteClient.ServiceReference1.SupprimerArticleRequest request) {
            return base.Channel.SupprimerArticleAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppJournalisteClient.ServiceReference1.SupprimerArticleResponse> SupprimerArticleAsync(string titre) {
            AppJournalisteClient.ServiceReference1.SupprimerArticleRequest inValue = new AppJournalisteClient.ServiceReference1.SupprimerArticleRequest();
            inValue.titre = titre;
            return ((AppJournalisteClient.ServiceReference1.GestionArticleWebService)(this)).SupprimerArticleAsync(inValue);
        }
    }
}
